# Generated by Django 5.2.8 on 2025-11-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='response',
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('user', 'Usuário'), ('bot', 'Bot')], default='user', max_length=5),
            preserve_default=False,
        ),
    ]
